---
title: "Making your code citable"
author: "RLadies Gainesville"
date: "May 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Useful links from the [Twitter thread](https://twitter.com/javirudolph/status/1126108566962737152)

 - <https://guides.github.com/activities/citable-code/>
 - <https://fairsharing.org/>
 - <https://www.re3data.org/>
    - This one is more for data, but can also include code.
    - This one is a good source for publishing your data sets.
 - <https://zenodo.org/>
 - <http://help.osf.io/m/addons/l/863982-connect-gitlab-to-a-project>
 - <https://choosealicense.com/>

# What is a DOI

A Digital Object Identifier ([DOI](https://en.wikipedia.org/wiki/Digital_object_identifier)) is a sort of long lasting reference used to manage/identify objects with a set of given standards. This is what you can use to give your code or repository a unique identifier.

# Why make your code citable?
 - Receive proper credit
 - Share with others in a 'formal' way
 - Keep track of its use
 - [another thread](https://twitter.com/Hao_and_Y/status/1126156562039476225)
 
 
 
# Authorship-related resources:
Most of these links are actually collected from the initial Twitter thread.  


 - Contributor Roles Taxonomy:
    - <https://www.casrai.org/credit.html>
 - Example from a real lab
    - <https://geocognitionresearchlaboratory.com/research-in-the-grl/authorship-agreements-training-students/>
 - Authorship in social sciences:
    - <https://link.springer.com/article/10.1007/s11192-018-2986-1>
 - On ecology example:
    - <https://swampthingecology.org/authorship.html>
 - A more stats-related approach:
    - <https://academia.stackexchange.com/questions/28690/when-does-a-statistical-consultant-become-a-co-author-or-collaborator/113924#113924>
    
    
# Summary points from the discussion with the group
 - Making data available and citable is valuable.
 - Difference between sharing raw data vs. clean data. 
 - When you don't own the data, but want to cite the code used to work with it:
    - Use simulated data or data with a simlar structure
    - R packages that can help: [charlatan](https://github.com/ropensci/charlatan) and [wakefield](https://github.com/trinker/wakefield)
 - We can all agree that having authorship discussions at the beginning is the best practice, but this doesn't always happen:
    - Friends or relatives asking for last minute help, join a sinking boat
    - Get on board with a project after a paper is rejected or addresses reviews
    - **most common** when graduate students need help last minute with their statistical analysis
        - This last situation tends to be problematic too because it doesn't involve an actual manuscript, but a thesis or dissertation with the *promise* of a manuscript. Also, based on personal experiences, the students don't always have a great motivation to tell their PI of the help they receive from the stats/coding person
 - Communication is **key** and some people are easier to talk to than others.
    - Don't write code on shared folders like Dropbox
    - Familiarize yourself and collaborators with GitHub or GitLab and share code this way instead. It gives a clearer picture of who's written the code and contributed to it.
    